###			https://www.github.com/UncP/Mini_Ray_Tracer			###

CPP 		 = g++
CPPFLAGS = -std=c++11 -Wall -O3

all:object.o sphere.o

object.o:object.hpp object.cpp
sphere.o:sphere.hpp sphere.cpp

clean:
	rm *.o