###			https://www.github.com/UncP/Mini_Ray_Tracer			###

CPP 		 = g++
CPPFLAGS = -std=c++11 -Wall -O3

all:random.o utility.o

random.o:random.hpp random.cpp
utility.o:utility.hpp utility.cpp

clean:
	rm *.o